#!/usr/bin/env python3
"""Shared types, routing rules, and utilities for context packet generation."""

from __future__ import annotations

import importlib.util
import re
import sys
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INDEX = Path(".ai-context/index.jsonl")
DEFAULT_ROUTING = Path(".ai-context/routing.yml")
DEFAULT_BUDGET = 700
MAX_SELECTED_CONTEXT_BUDGET = 1500
MAX_OMITTED = 6
PER_ROUTE_SELECTION_LIMIT = 2
GENERATED_PACKET_MARKER = "<!-- generated by scripts/context_pack.py -->"
STRICT_WARN_EXIT = 2
STRICT_FAIL_EXIT = 3

CURRENT_STATE_FILES = {
    "CONTEXT.md",
    "HANDOFF.md",
    "SPEC.md",
    "PLAN.md",
    "TODO.md",
    "VERIFY.md",
    "DECISIONS.md",
}
PROJECT_GUIDE_FILES = {"AGENTS.md", "LLM.md", "README.md"}
SOURCE_ROLE_PRIORITY = {
    "required": 600,
    "current_state": 500,
    "project_guidance": 300,
    "other": 200,
    "template": 100,
    "example": 0,
}


@dataclass(frozen=True)
class RouteSpec:
    """One routing rule for packet generation."""

    name: str
    label: str
    keywords: tuple[str, ...]
    files: tuple[str, ...]


@dataclass(frozen=True)
class LoadedRecord:
    """One fresh Markdown section with text."""

    file: str
    heading_path: tuple[str, ...]
    heading_level: int
    start_line: int
    end_line: int
    approx_token_estimate: int
    content_hash: str
    text: str

    def key(self) -> tuple[str, tuple[str, ...], int, int, int]:
        """Return a stable identity for stale-index checks."""
        return (
            self.file,
            self.heading_path,
            self.heading_level,
            self.start_line,
            self.end_line,
        )


@dataclass(frozen=True)
class RequiredFileResult:
    """Outcome for one required source."""

    file: str
    status: str
    detail: str
    represented_ranges: tuple[str, ...] = ()
    content_hashes: tuple[str, ...] = ()


def load_index_builder():
    """Load the index builder module without requiring package installation."""
    module_path = ROOT / "scripts" / "build_context_index.py"
    spec = importlib.util.spec_from_file_location("build_context_index", module_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"unable to load {module_path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


BUILD_INDEX = load_index_builder()

DEFAULT_ROUTES: tuple[RouteSpec, ...] = (
    RouteSpec(
        name="context_hydration",
        label="Context hydration",
        keywords=(
            "context hydration",
            "context packet",
            "context index",
            "context librarian",
            "working-context headroom",
            "hydrate",
            "hydration",
        ),
        files=(
            "docs/context-hydration.md",
            "scripts/context_pack.py",
            "scripts/build_context_index.py",
            ".ai-context/routing.yml",
            "tests/test_context_hydration.py",
        ),
    ),
    RouteSpec(
        name="resume_handoff",
        label="Resume / handoff",
        keywords=("handoff", "resume", "fresh context", "resume packet", "continuation"),
        files=(
            "HANDOFF.md",
            "CONTEXT.md",
            "templates/HANDOFF.md",
            "skills/handoff/SKILL.md",
            "docs/recipes.md",
        ),
    ),
    RouteSpec(
        name="verification",
        label="Verification",
        keywords=("verify", "verification", "evidence", "review required", "review_required"),
        files=(
            "VERIFY.md",
            "SPEC.md",
            "templates/VERIFY.md",
            "skills/verify-contract/SKILL.md",
            "skills/test-mini/SKILL.md",
            "docs/recipes.md",
        ),
    ),
    RouteSpec(
        name="scope_control",
        label="Scope control",
        keywords=("scope", "boundary", "freeze", "blast radius", "unrelated edits"),
        files=(
            "SPEC.md",
            "skills/scope-freeze/SKILL.md",
            "docs/recipes.md",
            "docs/skill-map.md",
        ),
    ),
    RouteSpec(
        name="planning",
        label="Planning",
        keywords=("plan", "spec", "checklist", "mini-spec", "thin-plan"),
        files=(
            "SPEC.md",
            "PLAN.md",
            "TODO.md",
            "skills/mini-spec/SKILL.md",
            "skills/checklist-mini/SKILL.md",
            "skills/thin-plan/SKILL.md",
            "templates/SPEC.md",
            "templates/PLAN.md",
        ),
    ),
    RouteSpec(
        name="debugging",
        label="Debugging",
        keywords=("debug", "bug", "diagnose", "failure", "regression", "loop"),
        files=(
            "skills/diagnose-loop/SKILL.md",
            "skills/bug-capture/SKILL.md",
            "docs/recipes.md",
        ),
    ),
    RouteSpec(
        name="shipping",
        label="Shipping",
        keywords=("ship", "release", "deploy", "publish", "rollout"),
        files=(
            "skills/ship-mini/SKILL.md",
            "docs/release-checklist.md",
            "docs/agent-worker-safety.md",
        ),
    ),
)

OVERVIEW_FALLBACK: tuple[RouteSpec, ...] = (
    RouteSpec(
        name="overview",
        label="Overview",
        keywords=("context", "overview", "docs", "readme", "start"),
        files=("CONTEXT.md", "README.md", "docs/skill-map.md", "docs/recipes.md"),
    ),
)


def normalize_text(text: str) -> str:
    """Normalize text for deterministic matching."""
    return re.sub(r"\s+", " ", text.lower()).strip()


def tokenize(text: str) -> list[str]:
    """Return lower-case word tokens."""
    return re.findall(r"[a-z0-9_]+", text.lower())


def normalized_content(text: str) -> str:
    """Normalize source text for exact-content deduplication."""
    return normalize_text(text)


def resolve_repo_path(root: Path, path: Path) -> Path:
    """Resolve a repository-relative path against the selected root."""
    return path if path.is_absolute() else root / path


def normalize_required_path(raw_path: str) -> tuple[str | None, str | None]:
    """Normalize and validate one required repository-relative path."""
    candidate = raw_path.strip().replace("\\", "/")
    if not candidate:
        return None, "required path is empty"
    pure = PurePosixPath(candidate)
    if pure.is_absolute():
        return None, f"required path must be repository-relative: {raw_path}"
    if any(part in {"", ".", ".."} for part in pure.parts):
        return None, f"required path contains an unsafe segment: {raw_path}"
    normalized = pure.as_posix()
    if normalized.startswith("/"):
        return None, f"required path must be repository-relative: {raw_path}"
    return normalized, None


def source_role(path: str, required_files: set[str] | None = None) -> str:
    """Classify a source by authority role."""
    if required_files and path in required_files:
        return "required"
    pure = PurePosixPath(path)
    if len(pure.parts) == 1 and pure.name in CURRENT_STATE_FILES:
        return "current_state"
    if pure.parts and pure.parts[0] == "templates":
        return "template"
    if (pure.parts and pure.parts[0] == "examples") or "examples" in pure.parts:
        return "example"
    if pure.name in PROJECT_GUIDE_FILES or (pure.parts and pure.parts[0] in {"skills", "docs"}):
        return "project_guidance"
    return "other"


def parse_positive_int(value: str) -> int:
    """Parse a positive integer from a routing scalar."""
    try:
        parsed = int(value)
    except ValueError as exc:
        raise ValueError(f"invalid integer value: {value}") from exc
    if parsed <= 0:
        raise ValueError("max_selected_context_tokens must be a positive integer")
    return parsed


def split_csv(value: str) -> list[str]:
    """Split a comma-separated scalar into trimmed values."""
    return [item.strip() for item in value.split(",") if item.strip()]


def parse_route_file(text: str) -> tuple[list[RouteSpec], int | None]:
    """Parse the small routing.yml format used by this repository."""
    routes: list[RouteSpec] = []
    configured_max_budget: int | None = None
    current_name: str | None = None
    current_label = ""
    current_keywords: list[str] = []
    current_files: list[str] = []
    seen_routes_header = False

    def flush() -> None:
        nonlocal current_name, current_label, current_keywords, current_files
        if current_name is None:
            return
        routes.append(
            RouteSpec(
                name=current_name,
                label=current_label or current_name.replace("_", " ").title(),
                keywords=tuple(item for item in current_keywords if item),
                files=tuple(item for item in current_files if item),
            )
        )
        current_name = None
        current_label = ""
        current_keywords = []
        current_files = []

    for raw_line in text.splitlines():
        line = raw_line.rstrip()
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue

        if not seen_routes_header:
            if stripped == "routes:":
                seen_routes_header = True
                continue
            if line.startswith(" ") or ":" not in stripped:
                raise ValueError(f"unexpected routing line before routes header: {line}")
            key, value = stripped.split(":", 1)
            if key == "max_selected_context_tokens":
                configured_max_budget = parse_positive_int(value.strip())
                continue
            raise ValueError(f"unsupported top-level key: {key}")

        if line.startswith("  ") and line.endswith(":") and line.count(":") == 1:
            flush()
            current_name = stripped[:-1]
            continue
        if current_name is None or not line.startswith("    ") or ":" not in stripped:
            raise ValueError(f"unexpected routing line: {line}")

        key, value = stripped.split(":", 1)
        value = value.strip()
        if key == "label":
            current_label = value
        elif key == "keywords":
            current_keywords = split_csv(value)
        elif key == "files":
            current_files = split_csv(value)
        else:
            raise ValueError(f"unsupported routing key: {key}")

    flush()
    if not seen_routes_header:
        raise ValueError("missing top-level routes: header")
    return routes, configured_max_budget


def load_routes(root: Path, routing_path: Path) -> tuple[list[RouteSpec], list[str], str, int]:
    """Load routing rules with a deterministic built-in fallback."""
    path = resolve_repo_path(root, routing_path)
    warnings: list[str] = []
    if not path.exists():
        warnings.append(f"routing file missing: {path}")
        return list(DEFAULT_ROUTES), warnings, "built-in", MAX_SELECTED_CONTEXT_BUDGET
    try:
        routes, configured_max_budget = parse_route_file(path.read_text(encoding="utf-8"))
    except OSError as exc:
        warnings.append(f"unable to read routing file: {exc}")
        return list(DEFAULT_ROUTES), warnings, "built-in", MAX_SELECTED_CONTEXT_BUDGET
    except ValueError as exc:
        warnings.append(f"routing file parse failed: {exc}")
        return list(DEFAULT_ROUTES), warnings, "built-in", MAX_SELECTED_CONTEXT_BUDGET

    if not routes:
        warnings.append("routing file did not define any routes")
        return list(DEFAULT_ROUTES), warnings, "built-in", MAX_SELECTED_CONTEXT_BUDGET

    max_budget = configured_max_budget or MAX_SELECTED_CONTEXT_BUDGET
    if max_budget > MAX_SELECTED_CONTEXT_BUDGET:
        warnings.append(
            f"routing max_selected_context_tokens {max_budget} exceeds hard max "
            f"{MAX_SELECTED_CONTEXT_BUDGET}; clamped to {MAX_SELECTED_CONTEXT_BUDGET}"
        )
        max_budget = MAX_SELECTED_CONTEXT_BUDGET
    return routes, warnings, "file", max_budget


def clamp_budget(requested_budget: int, max_budget: int) -> tuple[int, list[str]]:
    """Clamp a requested packet budget and return visible notes."""
    if requested_budget <= max_budget:
        return requested_budget, []
    return max_budget, [
        f"requested budget {requested_budget} exceeds max {max_budget}; clamped to {max_budget}"
    ]


def select_routes(task_text: str, routes: list[RouteSpec]) -> list[tuple[RouteSpec, int]]:
    """Rank routes against the task string."""
    normalized_task = normalize_text(task_text)
    task_tokens = set(tokenize(task_text))
    ranked: list[tuple[RouteSpec, int]] = []
    for route in routes:
        score = sum(
            1
            for keyword in route.keywords
            if normalize_text(keyword) and normalize_text(keyword) in normalized_task
        )
        route_tokens = set(tokenize(route.name.replace("_", " ")) + tokenize(route.label))
        score += len(task_tokens & route_tokens)
        if score > 0:
            ranked.append((route, score))
    ranked.sort(key=lambda item: (-item[1], routes.index(item[0])))
    return ranked


def record_search_text(record: LoadedRecord) -> str:
    """Return normalized searchable text for a record."""
    return normalize_text(" ".join([record.file, " ".join(record.heading_path), record.text]))


def format_heading_path(heading_path: tuple[str, ...]) -> str:
    """Format a heading path for display."""
    return "(file root)" if not heading_path else " > ".join(heading_path)


def escape_table_cell(value: object) -> str:
    """Escape Markdown table metacharacters."""
    text = str(value).replace("\\", "\\\\")
    return text.replace("|", "\\|").replace("`", "&#96;").replace("\n", " ")


def safe_fence(text: str) -> tuple[str, str]:
    """Return opening and closing fences that cannot collide with source text."""
    max_backticks = max((len(match.group(0)) for match in re.finditer(r"`+", text)), default=0)
    max_tildes = max((len(match.group(0)) for match in re.finditer(r"~+", text)), default=0)
    backtick_len = max(4, max_backticks + 1)
    tilde_len = max(4, max_tildes + 1)
    if backtick_len <= tilde_len:
        fence = "`" * backtick_len
    else:
        fence = "~" * tilde_len
    return f"{fence}md", fence
